baseURL = "https://my-sakura.netlify.app"
languageCode = "zh-Hans"
defaultContentLanguage = "zh"
title = "my-sakura 的博客"
theme = "dream"

copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />本作品采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。'

googleAnalytics = "UA-180228758-1"

disqusShortname = "my-sakura"

enableRobotsTXT = true

hasCJKLanguage = true

# Paginate = 4

[outputs]
  home = ["HTML", "RSS", "JSON"]

# https://gohugo.io/news/0.60.0-relnotes/
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  background = "black"
  backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  images = ["me/background.jpg"] 

  author = "sakura"  
  description = "sakura 的生活记录～"
  avatar = "/me/qq.png"
  motto = "不管做什么都不要为自己找借口。"
  categoriesLimitInHeader = 6
  # headerBottomText = ""

  rss = true

  utterancesRepo = "hugo-blog/my-Sakura.github.io"

  # valine = true
  # LEANCLOUD_APP_ID = ""
  # LEANCLOUD_APP_KEY = ""
  
  email = "liu1771451233@gmail.com"
  # twitter = ""
  # facebook = "g1eny0ung"
  # instagram = "g1eny0ung"
  # mastodon = ""
  # linkedin = "g1eny0ung"
  github = "my-Sakura"
  # stackoverflow = "5676489/g1eny0ung"
  # codepen = "g1eny0ung"

  siteStartYear = 2020

  favicon = "/favicon.ico"

  highlightjs = true
  # highlightjsCDN = "https://cdn.jsdelivr.net/gh/highlightjs/cdn-release/build/highlight.min.js"
  highlightjsExtraLanguages = ["ocaml"]
  highlightjsTheme = "gruvbox-light"
  highlightjsThemeDark = "gruvbox-dark"

  # search
  enableSearch = true

  # options
  showSummaryCoverInPost = true
  # hasTwitterEmbed = true

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true
  dark404 = true
